// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQv2KMG-D4v1talnwokcjI4ReaVNBTk2A',
    appId: '1:465876456943:web:4c26afdeacff354b28121a',
    messagingSenderId: '465876456943',
    projectId: 'ebra-cf544',
    authDomain: 'ebra-cf544.firebaseapp.com',
    storageBucket: 'ebra-cf544.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHLd61mMP73rleoDZ8CMb1PMsPyQ5Zt0',
    appId: '1:465876456943:android:ab4f67ed9219f62d28121a',
    messagingSenderId: '465876456943',
    projectId: 'ebra-cf544',
    storageBucket: 'ebra-cf544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6BMV5MPW4amEeBXH2X1Z5MBXu7LFPDm8',
    appId: '1:465876456943:ios:8e9564297700268328121a',
    messagingSenderId: '465876456943',
    projectId: 'ebra-cf544',
    storageBucket: 'ebra-cf544.firebasestorage.app',
    iosBundleId: 'com.example.ebra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6BMV5MPW4amEeBXH2X1Z5MBXu7LFPDm8',
    appId: '1:465876456943:ios:8e9564297700268328121a',
    messagingSenderId: '465876456943',
    projectId: 'ebra-cf544',
    storageBucket: 'ebra-cf544.firebasestorage.app',
    iosBundleId: 'com.example.ebra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQv2KMG-D4v1talnwokcjI4ReaVNBTk2A',
    appId: '1:465876456943:web:a1b6eb6983c46ebf28121a',
    messagingSenderId: '465876456943',
    projectId: 'ebra-cf544',
    authDomain: 'ebra-cf544.firebaseapp.com',
    storageBucket: 'ebra-cf544.firebasestorage.app',
  );
}
